language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: true
go_import_path: gitlab.musadisca-games.com/wangxw/musae/framework/errorx
before_install:
  - go get gitlab.musadisca-games.com/wangxw/musae/framework/errorx
  - go get gitlab.musadisca-games.com/wangxw/musae/framework/go-queue
script:
  - go build example/main.go
  - go test ./
notifications:
  email: false
